---
title: "Tugas MPDW R2"
author: "Afiq Dzakwan Anasti - G1401231058"
date: "`r Sys.Date()`"
output: html_document
---

# 1. Import libraries, data, & time series
```{r}
library(readxl)
library(ggplot2)
library(TTR)
library(forecast)
library(Metrics)
library(tidyr)
library(dplyr)
```

```{r}
# Import data
data <- read_xlsx("D:/Kuliah/Semester 5/MPDW2/Tugas/dataudarajkt.xlsx")
data
```

```{r}
# Buat time series (harian)
data$tanggal <- as.Date(data$tanggal, format = "%Y/%M/%D")
pm10_ts <- ts(data$pm10, frequency = 365)
data
```

# 2. Eksplorasi Data
```{r}
str(data)
summary(data)
```

```{r}
ts.plot(pm10_ts, xlab="Tanggal", ylab="PM10", 
        main = "Time Series Plot")
points(pm10_ts)
```

# 3. Data split
```{r}
# Split data (80% train, 20% test)
n <- length(pm10_ts)
train_size <- floor(0.8 * n)

train.ts <- pm10_ts[1:train_size]
test.ts  <- pm10_ts[(train_size+1):n]

test_dates <- data$tanggal[(train_size+1):n]
```

```{r}
# Plot train & test
plot(train.ts, col="blue",main="Plot Data Latih")
points(train.ts)

plot(test.ts, col="blue",main="Plot Data Uji")
points(test.ts)
```

```{r}
# Data frame untuk train
train_df <- data.frame(
  Period = 1:length(train.ts),   # indeks dari 1 sampai panjang train
  pm10 = as.numeric(train.ts),
  Tipe = "Data Latih"
)

# Data frame untuk test
test_df <- data.frame(
  Period = (length(train.ts)+1):(length(train.ts)+length(test.ts)),  # lanjut dari akhir train
  pm10 = as.numeric(test.ts),
  Tipe = "Data Uji"
)

# Gabung jadi satu
plot_df <- rbind(train_df, test_df)

# Plot
ggplot(plot_df, aes(x = Period, y = pm10, col = Tipe)) + 
  geom_line() +
  labs(x = "Periode Waktu", y = "PM10", color = "Keterangan:") +
  scale_colour_manual(values = c("Data Latih" = "blue", "Data Uji" = "red")) +
  theme_bw() + 
  theme(legend.position = "bottom",
        plot.caption = element_text(hjust=0.5, size=12))

```


# 4. Forecast tiap model
```{r}
# SMA
sma <- SMA(train.ts)
sma_fitted <- sma
sma_forecast <- rep(tail(na.omit(sma), 1), length(test.ts))
acc_sma <- data.frame(
  Model = "SMA",
  SSE = sum((test.ts - sma_forecast)^2),
  MSE = mean((test.ts - sma_forecast)^2),
  MAE = mae(test.ts, sma_forecast),
  RMSE = rmse(test.ts, sma_forecast),
  MAPE = mape(test.ts, sma_forecast)
)

# DMA
dma <- SMA(na.omit(sma))
dma_fitted <- dma
dma_forecast <- rep(tail(na.omit(dma), 1), length(test.ts))
acc_dma <- data.frame(
  Model = "DMA",
  SSE = sum((test.ts - dma_forecast)^2),
  MSE = mean((test.ts - dma_forecast)^2),
  MAE = mae(test.ts, dma_forecast),
  RMSE = rmse(test.ts, dma_forecast),
  MAPE = mape(test.ts, dma_forecast)
)

# SES
ses_model <- ses(train.ts, h = length(test.ts))
ses_fitted <- ses_model$fitted
ses_forecast <- as.numeric(ses_model$mean)
acc_ses <- data.frame(
  Model = "SES",
  SSE = sum((test.ts - ses_forecast)^2),
  MSE = mean((test.ts - ses_forecast)^2),
  MAE = mae(test.ts, ses_forecast),
  RMSE = rmse(test.ts, ses_forecast),
  MAPE = mape(test.ts, ses_forecast)
)

# DES
des_model <- holt(train.ts, h = length(test.ts))
des_fitted <- des_model$fitted
des_forecast <- as.numeric(des_model$mean)
acc_des <- data.frame(
  Model = "DES",
  SSE = sum((test.ts - des_forecast)^2),
  MSE = mean((test.ts - des_forecast)^2),
  MAE = mae(test.ts, des_forecast),
  RMSE = rmse(test.ts, des_forecast),
  MAPE = mape(test.ts, des_forecast)
)

# Holt-Winters
hw_model <- HoltWinters(train.ts, beta = TRUE, gamma = FALSE)
hw_fitted <- hw_model$fitted[,1] 
hw_forecast <- forecast(hw_model, h = length(test.ts))
hw_forecast_values <- as.numeric(hw_forecast$mean)
acc_hw <- data.frame(
  Model = "Holt-Winters",
  SSE = sum((test.ts - hw_forecast_values)^2),
  MSE = mean((test.ts - hw_forecast_values)^2),
  MAE = mae(test.ts, hw_forecast_values),
  RMSE = rmse(test.ts, hw_forecast_values),
  MAPE = mape(test.ts, hw_forecast_values)
)

# Gabungkan semua
acc_all <- rbind(acc_sma, acc_dma, acc_ses, acc_des, acc_hw)
print(acc_all)
```

Berdasarkan hasil perhitungan, metode Single Exponential Smoothing (SES) merupakan model peramalan terbaik karena menghasilkan nilai error yang paling kecil pada seluruh ukuran evaluasi (SSE, MSE, MAE, RMSE, dan MAPE).


# 5. Plot perbandingan
```{r}
forecast_df <- data.frame(
  tanggal = test_dates,
  SMA = sma_forecast,
  DMA = dma_forecast,
  SES = ses_forecast,
  DES = des_forecast,
  HW = hw_forecast_values,
  Actual = as.numeric(test.ts)
)

forecast_long <- forecast_df %>%
  pivot_longer(
    cols = -tanggal,
    names_to = "Model",
    values_to = "pm10"
  )

ggplot(forecast_long, aes(x = tanggal, y = pm10, color = Model)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Perbandingan Actual vs Forecast",
    x = "Tanggal", y = "Nilai Kurs Beli"
  ) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b-%Y") +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 90, hjust = 1, size = 6)
  )
```
