---
title: "Tugas Kuliah MPDW Pert 2"
author: "Cameliya Ulya Hidayah_G1401231026"
date: "2025-08-29"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(readxl)
library(GGally)
library(psych)
library(car)
library(carData)
library(corrplot)
library(dplyr)
library(stargazer)
library(olsrr)
library(lmtest)
```

```{r}
df <- read_xlsx("C:/Users/camel/Downloads/IPM Kota Pekanbaru.xlsx")
df
```

# Eksplorasi Data
```{r}
pairs.panels(df)
```

```{r}
str(df)
```


```{r}
summary(df)
colSums(is.na(df))
```

```{r}
hist(df$IPM)
```

```{r}
boxplot(df$IPM)
```


```{r}
# Misalnya model linear regresi sederhana (ubah sesuai modelmu)
model <- lm(IPM ~ Tahun, data = df)   # atau IPM ~ variabel lain
summary(model)
```


```{r}
# Residuals
resid <- residuals(model)
fitted <- fitted.values(model)

# 1. Normal Probability Plot (QQ Plot)
qqPlot(model, main="Normal Probability Plot of the Residuals")
```


```{r}
# 2. Residuals vs Fitted
plot(fitted, resid, 
     xlab="Fitted Value", ylab="Residual",
     main="Residuals Versus the Fitted Values")
abline(h=0, col="red")
```


```{r}
# 3. Histogram Residuals
hist(resid, breaks=10, col="grey", 
     main="Histogram of the Residuals", xlab="Residual")
```


```{r}
# 4. Residuals vs Order
plot(resid, type="o", 
     main="Residuals Versus the Order of the Data",
     xlab="Observation Order", ylab="Residual")
```


```{r}
# 5. Autocorrelation Function (ACF)
acf(resid, main="Autocorrelation Function for Residuals")
```


```{r}
# 6. Partial Autocorrelation Function (PACF)
pacf(resid, main="Partial Autocorrelation Function for Residuals")
```

```{r, warning=FALSE}
dwtest(model)
```


